package br.com.eurotech.treinamentos.model;

public enum Setor {
    PRODUCAO,
    CONTROLE_DE_QUALIDADE,
    ASSUNTOS_REGULATORIOS,
    VALIDACAO,
    SUPRIMENTOS_E_LOGISTICA,
    MANUTENCAO_INDUSTRIAL,
    SEGURANCA_DO_TRABALHO,
    ENGENHARIA_DE_PROCESSOS,
    GESTAO_DE_RESIDUOS,
    ARMAZENAGEM_E_DISTRIBUICAO,
    FARMACOVIGILANCIA;
}
